/* mt/cb/mt_win32.h */

/* Copyright (C) 1998, RSA Data Security Pty Ltd.
 *
 * This file shall only be used to demonstrate how to interface to an
 * RSA Data Security Pty Ltd licensed development product.
 *
 * You have a royalty-free right to use, reproduce and distribute this 
 * demonstration file, provided that you agree that RSA Data Security Pty Ltd
 * has no warranty, implied or otherwise, or liability for this 
 * demonstration file.
 *
 */

#ifndef HEADER_MT_CB_MT_WIN32_H 
#define HEADER_MT_CB_MT_WIN32_H 

#include <windows.h>
typedef HANDLE APP_THREAD_ID;

#endif /* HEADER_MT_CB_MT_WIN32_H */

