//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;
using System.Configuration;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
// Use tempuri.org for local testing.
//[System.Web.Services.WebServiceBindingAttribute(Name="IncomingQueueSoap", Namespace="http://tempuri.org/")]
// Use www.ctl.com/webservices/rbs/ for production
[System.Web.Services.WebServiceBindingAttribute(Name="IncomingQueueSoap", Namespace="http://www.ctl.com/webservices/rbs/")]
public class IncomingQueue : System.Web.Services.Protocols.SoapHttpClientProtocol 
{
    
    /// <remarks/>
    public IncomingQueue() {
        this.Url = ConfigurationSettings.AppSettings["fraudguard.url"];	
    }
    
    /// <remarks/>
	// Use tempuri.org for local testing.
	//[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Send", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	// Use www.ctl.com/webservices/rbs/ for production
	[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ctl.com/webservices/rbs/Send", RequestNamespace="http://www.ctl.com/webservices/rbs/", ResponseNamespace="http://www.ctl.com/webservices/rbs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
	public string Send(string cXmlMsg) 
	{
        object[] results = this.Invoke("Send", new object[] {
                    cXmlMsg});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSend(string cXmlMsg, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Send", new object[] {
                    cXmlMsg}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSend(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
}
