//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TranPosSearch.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TRANSETYPE                  129
#define IDD_TRAN_INQUIRY                130
#define IDD_IDLE_LOGIN                  131
#define IDD_TRANDETAILS                 213
#define IDC_ACCOUNT_NBR_FLD             1001
#define IDC_MERCHANT_ID_FLD             1002
#define IDC_DEVICE_ID_FLD               1003
#define IDC_DATE_FLD                    1004
#define IDC_TIME_FLD                    1005
#define IDC_LIST                        1011
#define IDC_NEXT_BUTTON                 1012
#define IDC_MESSAGE_LBL                 1013
#define IDC_INQUIRY_BUTTON              1015
#define IDC_DETAILS_BUTTON              1016
#define IDC_TEXT_FLD                    1017
#define IDC_DATE_END_FLD                1018
#define IDC_EMV_FLD                     1018
#define IDC_TIME_END_FLD                1019
#define IDC_EMV_FLD2                    1019
#define IDC_EXP_DATE_FLD                1025
#define IDC_ACQUIRING_INST_ID_FLD       1026
#define IDC_FORWARDING_INSTITUTION_ID_FLD 1027
#define IDC_OUTSTANDING_BALANCE_FLD     1028
#define IDC_CREDIT_LIMIT_FLD            1029
#define IDC_OPERATOR_ID_FLD             1030
#define IDC_CURRENCY_CODE_FLD           1031
#define IDC_SYSTEM_DATE_FLD             1032
#define IDC_FG_Result_FLD               1033
#define IDC_VIEW_ACCEPTED_RADIO         1034
#define IDC_BIN_LOW                     1034
#define IDC_VIEW_FAILED_RADIO           1035
#define IDC_BDO_MERC_ACQ_TX             1035
#define IDC_BIN_HIGH                    1035
#define IDC_VIEW_ALLRADIO               1036
#define IDC_ORIGINAL_CURRENCY_CODE      1036
#define IDC_RESEND_BUTTON               1037
#define IDC_EARMARKED_AMT               1037
#define IDC_VIEW_FGRAW_RADIO            1038
#define IDC_AUTH_PROFILE                1038
#define IDC_POSTRAN_GROUP               1039
#define IDC_SERVICE_CODE                1039
#define IDC_BIN_TYPE                    1039
#define IDC_EMV_RAW_RADIO               1040
#define IDC_VISA_MERCHANT_IND           1040
#define IDC_BIN_CARD_FAMILY             1040
#define IDC_FGUARDTRAN_GROUP            1041
#define IDC_DIGITAL_COMM_PRG_IND        1041
#define IDC_DIGITAL_ENTRY_IDENTIFIER    1042
#define IDC_POS_SEARCH_CHECK            1045
#define IDC_FGUARD_SEARCH_CHECK         1046
#define IDC_FG_Result                   1047
#define IDC_RADIO2                      1049
#define IDC_GROSS_AMOUNT                1050
#define IDC_MONTHLY_AMORT               1051
#define IDC_TERM_LENGTH                 1052
#define IDC_FACTOR                      1053
#define IDC_UID                         1055
#define IDC_PWD                         1056
#define IDC_USER                        1057
#define IDC_PASS                        1058
#define IDC_BUTTON_EXIT                 1060
#define IDC_STATIC_APP_VERSION          1062
#define IDC_MASK_CARD_NUMBER_CHK        1063
#define IDC_CHECK1                      1064
#define IDC_ATP_STIP                    1064
#define IDC_CHECK2                      1065
#define IDC_MERCHANT_OMD                1065
#define IDC_CHECK3                      1066
#define IDC_VOICE_VOD                   1066
#define IDC_CHECK4                      1067
#define IDC_CVV2_Present                1067
#define IDC_SCHEME_STIP                 1068
#define IDC_TERMINAL_ID_FLD             1084
#define IDC_Orginial_Txn_Amount         1085
#define IDC_Original_Txn_Amt_Currency   1086
#define IDC_ECI                         1087
#define IDC_MCC                         1089
#define IDC_Merchant_Name               1091
#define IDC_POS_DATA                    1092
#define IDC_HOST_PROCESSED              1094
#define IDC_CVV_PRESENT                 1096
#define IDC_Validated                   1097
#define IDC_CVV_Validated               1097
#define IDC_CVV                         1099
#define IDC_CVV2_Validated              1100
#define IDC_PIN_Present                 1101
#define IDC_PIN_Validated               1102
#define IDC_ARQC_Present                1103
#define IDC_CAVV_Present                1104
#define IDC_CAVV_Validated              1105
#define IDC_Acquiring_Country           1107
#define IDC_ARQC_VALIDATED              1108
#define IDC_RETRIEVAL_REF_NUM_FLD       1223
#define IDC_TRAN_TYPE_FLD               1224
#define IDC_PROCESSING_CODE_FLD         1225
#define IDC_CARD_NUMBER_FLD             1226
#define IDC_TRAN_AMOUNT_FLD             1227
#define IDC_RESPONSE_CODE_FLD           1228
#define IDC_MERCHANT_ID_FLD1            1229
#define IDC_INVOICE_NUMBER_FLD          1230
#define IDC_SYSTEM_TRACE_NUMBER_FLD     1231
#define IDC_MESSAGE_TYPE                1232
#define IDC_TRAN_TIME_FLD               1233
#define IDC_TRAN_DATE_FLD               1234
#define IDC_AUTH_ID_RESPONSE_FLD        1235
#define IDC_RESPONSE_TEXT_FLD           1236
#define IDC_TRAN_NII                    1237
#define IDC_POS_ENTRY_MODE_FLD          1239
#define IDC_POS_CONDITION_CODE_FLD      1242
#define IDS_PRODUCT_VERSION             61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
