
#define MT_XCOM_GUI_LOGIN			200
#define ST1_XCOM_GUI_RELOGIN		1
#define MT_XCOM_GUI_LOGOUT			201

#define MT_XCOM_GUI_USER			202
#define ST1_XCOM_GUI_USER_CREATE	1
#define ST1_XCOM_GUI_USER_DELETE	2
#define ST1_XCOM_GUI_USER_READ		3
#define ST1_XCOM_GUI_USER_WRITE		4

#define MT_XCOM_GUI_QUE			203
#define ST1_XCOM_GUI_QUE_CREATE		1
#define ST1_XCOM_GUI_QUE_DELETE		2
#define ST1_XCOM_GUI_QUE_READ		3
#define ST1_XCOM_GUI_QUE_WRITE		4

#define MT_XCOM_GUI_MEM			204
#define ST1_XCOM_GUI_MEM_CREATE		1
#define ST1_XCOM_GUI_MEM_DELETE		2
#define ST1_XCOM_GUI_MEM_READ		3
#define ST1_XCOM_GUI_MEM_WRITE		4

#define MT_XCOM_GUI_ACK_LOGIN       220
#define ST1_XCOM_GUI_ACK_RELOGIN	 1
#define MT_XCOM_GUI_ACK_LOGOUT      221

#define MT_XCOM_GUI_ACK_USER        222
#define ST1_XCOM_GUI_ACK_USER_CREATE 1
#define ST1_XCOM_GUI_ACK_USER_DELETE 2
#define ST1_XCOM_GUI_ACK_USER_READ   3
#define ST1_XCOM_GUI_ACK_USER_WRITE  4

#define MT_XCOM_GUI_ACK_QUE         223
#define ST1_XCOM_GUI_ACK_QUE_CREATE  1
#define ST1_XCOM_GUI_ACK_QUE_DELETE  2
#define ST1_XCOM_GUI_ACK_QUE_READ    3
#define ST1_XCOM_GUI_ACK_QUE_WRITE   4


#define MT_XCOM_GUI_ACK_MEM         224
#define ST1_XCOM_GUI_ACK_MEM_CREATE  1
#define ST1_XCOM_GUI_ACK_MEM_DELETE  2
#define ST1_XCOM_GUI_ACK_MEM_READ    3
#define ST1_XCOM_GUI_ACK_MEM_WRITE   4

#define MT_XCOM_GUI_STATUS_UPDATE   225

#define MT_XCOM_GUI_FLUSH			 226
#define MT_XCOM_GUI_FLUSH_ACK		 227







