//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by monitordco.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MONITORDCO_FORM             101
#define IDR_MAINFRAME                   128
#define IDR_MONITOTYPE                  129
#define IDD_PRIMARYACCOUNT_SELECTION    131
#define IDD_MONITOR_FORM1               132
#define IDD_ADVICES                     132
#define IDB_TESTOFF                     134
#define IDB_TESTING                     135
#define IDB_NC_RED                      136
#define IDB_NC_GREEN                    137
#define IDB_NC_YELLOW                   138
#define IDR_241                         141
#define IDD_MONITORDCO_FORM_Orignial    999
#define IDC_NETWORK_STATUS              1001
#define IDC_REFRESH                     1002
#define IDC_ECHOTEST                    1003
#define IDC_LOGOFF                      1004
#define IDC_LOGON                       1005
#define IDC_LOG_MESSAGES                1006
#define IDC_CLOSE                       1007
#define IDC_PRIMARYACCOUNT_LIST         1007
#define IDC_CLEARLOG                    1008
#define IDC_SAVELOG                     1009
#define IDC_SAF                         1010
#define IDC_DIALOG_CONNECT_STATUS       1011
#define IDC_DIALOG_CONNECT_STATUS2      1012
#define IDC_SCROLLBAR2                  1013
#define IDC_LOGON2                      1013
#define IDC_SCROLLBAR3                  1014
#define IDC_LOGOFF2                     1014
#define IDC_SCROLLBAR4                  1015
#define IDC_ECHOTEST2                   1015
#define IDC_CONTROLLER_ACTIVITY         1016
#define IDC_SAF2                        1016
#define IDC_BUTTON1                     1017
#define IDC_RESET_COUNTS_BUTTON         1017
#define IDC_START_ADVICES               1017
#define IDC_TRAN_ACTIVITY_LIST          1018
#define IDC_SERVICE_NAME_LABEL          1019
#define IDC_CUP_KEY_REQ_BUTTON          1019
#define IDC_RECEIVED_LABEL              1020
#define IDC_CUP_KEY_UPDATE_BUTTON       1020
#define IDC_LOG_DATE_LABEL              1021
#define IDC_LOG_SERVICE_LABEL           1022
#define IDC_SENT_LABEL                  1023
#define IDC_REFRESH2                    1023
#define IDC_RATE_LABEL                  1024
#define IDC_TRAN_ACTIVITY_LIST2         1024
#define IDC_PING_BUTTON                 1025
#define IDC_PING_DIALOG_BUTTON1         1026
#define IDC_LOG_TYPE_LABEL              1027
#define IDC_LOG_MSG_LABEL               1028
#define IDC_STOP_ADVICES                1028
#define IDC_LOG_TIME_LABEL              1029
#define IDC_EXIT                        1030
#define IDC_CUP_KEY_UPDATE_BUTTON2      1030
#define IDC_CUP_KEY_RELOAD              1030
#define IDC_TEST_BUTTON                 1031
#define IDC_TEST_RESULT                 1032
#define IDC_STATIC_APPVERSION           1033
#define IDC_NC_STATUS                   1033
#define IDC_STATIC_APP_VERSION          1034
#define IDC_CHECK1                      1034
#define IDC_ACQUIRER_OFF                1035
#define IDC_MGT_REQUESTS                1036
#define IDC_PING_DIALOG_BUTTON2         1036
#define IDC_STIP_REQUESTS               1037
#define IDC_PING_BUTTON2                1037
#define IDC_STIP_REQUESTS2              1038
#define IDC_RESET_COUNTS_BUTTON2        1038
#define IDC_NET_TRAN_LIST               1039
#define IDC_LOG_MESSAGES2               1040
#define IDC_PING                        1041
#define IDC_SAVELOG2                    1042
#define IDC_MONITOR1_NAME               1043
#define IDC_CLEARLOG2                   1044
#define IDC_TEST_BUTTON2                1045
#define IDC_TEST_RESULT2                1046
#define IDC_LOG_DATE_LABEL2             1047
#define IDC_LOG_SERVICE_LABEL2          1048
#define IDC_LOG_TYPE_LABEL2             1049
#define IDC_LOG_MSG_LABEL2              1050
#define IDC_LOG_TIME_LABEL2             1051
#define IDC_NC_STATUS2                  1052
#define IDC_CHECK2                      1053
#define IDC_ACQUIRER_OFF2               1054
#define IDC_NET_TRAN_LIST2              1055
#define IDC_PING2                       1056
#define IDC_NETWORK_STATUS2             1057
#define IDC_CUP_KEY_REQ_BUTTON2         1058
#define IDC_CUP_KEY_UPDATE_BUTTON3      1059
#define IDC_CUP_KEY_RELOAD2             1060
#define IDC_MONITOR2_NAME               1061
#define IDC_DIALOG_CONNECT_STATUS3      1062
#define IDC_LOGON3                      1063
#define IDC_LOGOFF3                     1064
#define IDC_ECHOTEST3                   1065
#define IDC_SAF3                        1066
#define IDC_REFRESH3                    1067
#define IDC_PING_DIALOG_BUTTON3         1068
#define IDC_TRAN_ACTIVITY_LIST3         1069
#define IDC_PING_BUTTON3                1070
#define IDC_RESET_COUNTS_BUTTON3        1071
#define IDC_LOG_MESSAGES3               1072
#define IDC_SAVELOG3                    1073
#define IDC_CLEARLOG3                   1074
#define IDC_TEST_BUTTON3                1075
#define IDC_TEST_RESULT3                1076
#define IDC_LOG_DATE_LABEL3             1077
#define IDC_LOG_SERVICE_LABEL3          1078
#define IDC_LOG_TYPE_LABEL3             1079
#define IDC_LOG_MSG_LABEL3              1080
#define IDC_LOG_TIME_LABEL3             1081
#define IDC_NC_STATUS3                  1082
#define IDC_CHECK3                      1083
#define IDC_ACQUIRER_OFF3               1084
#define IDC_NET_TRAN_LIST3              1085
#define IDC_PING3                       1086
#define IDC_NETWORK_STATUS3             1087
#define IDC_CUP_KEY_REQ_BUTTON3         1088
#define IDC_CUP_KEY_UPDATE_BUTTON4      1089
#define IDC_CUP_KEY_RELOAD3             1090
#define IDC_MONITOR3_NAME               1091
#define IDC_DIALOG_CONNECT_STATUS4      1092
#define IDC_LOGON4                      1093
#define IDC_LOGOFF4                     1094
#define IDC_ECHOTEST4                   1095
#define IDC_SAF4                        1096
#define IDC_REFRESH4                    1097
#define IDC_PING_DIALOG_BUTTON4         1098
#define IDC_TRAN_ACTIVITY_LIST4         1099
#define IDC_PING_BUTTON4                1100
#define IDC_RESET_COUNTS_BUTTON4        1101
#define IDC_LOG_MESSAGES4               1102
#define IDC_SAVELOG4                    1103
#define IDC_CLEARLOG4                   1104
#define IDC_TEST_BUTTON4                1105
#define IDC_TEST_RESULT4                1106
#define IDC_LOG_DATE_LABEL4             1107
#define IDC_LOG_SERVICE_LABEL4          1108
#define IDC_LOG_TYPE_LABEL4             1109
#define IDC_LOG_MSG_LABEL4              1110
#define IDC_LOG_TIME_LABEL4             1111
#define IDC_NC_STATUS4                  1112
#define IDC_CHECK4                      1113
#define IDC_ACQUIRER_OFF4               1114
#define IDC_NET_TRAN_LIST4              1115
#define IDC_PING4                       1116
#define IDC_NETWORK_STATUS4             1117
#define IDC_CUP_KEY_REQ_BUTTON4         1118
#define IDC_CUP_KEY_UPDATE_BUTTON5      1119
#define IDC_CUP_KEY_RELOAD4             1120
#define IDC_MONITOR4_NAME               1121
#define IDC_TAB3                        1122
#define IDC_DIALOG_ID_LABEL3            1123
#define IDC_LOG_STATUS_LABEL3           1124
#define IDC_NAME_LABEL3                 1125
#define IDC_TAB1                        1126
#define IDC_DIALOG_ID_LABEL             1127
#define IDC_LOG_STATUS_LABEL            1128
#define IDC_NAME_LABEL                  1129
#define IDC_DIALOG_ID_LABEL2            1130
#define IDC_LOG_STATUS_LABEL2           1131
#define IDC_NAME_LABEL2                 1132
#define IDC_DIALOG_ID_LABEL4            1133
#define IDC_LOG_STATUS_LABEL4           1134
#define IDC_NAME_LABEL4                 1135
#define IDC_TAB2                        1136
#define IDC_CHECK5                      1137
#define IDC_TAB4                        1138
#define IDC_MFCCOLORBUTTON1             1139
#define IDC_TEST_RESULT5                1139
#define IDB_MONITOR1                    1140
#define IDC_TEST_RESULT6                1140
#define IDB_MONITOR2                    1141
#define IDC_TEST_RESULT7                1141
#define IDB_MONITOR3                    1142
#define IDC_TEST_RESULT8                1142
#define IDB_MONITOR4                    1143
#define IDS_PRODUCT_VERSION             61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
