
INT FALCON_read_CUP_merchant_indicator(void);
INT FALCON_read_CUP_MP_Bin_range_1_indicator(void);
INT FALCON_read_CUP_MP_Bin_range_2_indicator(void);
INT FALCON_read_CUP_MP_Bin_range_3_indicator(void);
INT FALCON_read_CUP_MP_Bin_range_4_indicator(void);
INT FALCON_read_CUP_MP_Bin_range_5_indicator(void);
INT FALCON_read_CUP_MP_Bin_range_len_1(void);
INT FALCON_read_CUP_MP_Bin_range_len_2(void);
INT FALCON_read_CUP_MP_Bin_range_len_3(void);
INT FALCON_read_CUP_MP_Bin_range_len_4(void);
INT FALCON_read_CUP_MP_Bin_range_len_5(void);


void FALCON_build_request_HeaderFile();
void FALCON_build_request_field_1( );
void FALCON_build_request_field_2( );
void FALCON_build_request_field_3( );
void FALCON_build_request_field_4( );
void FALCON_build_request_field_5( );
void FALCON_build_request_field_6( );
void FALCON_build_request_field_7( );
void FALCON_build_request_field_8( );
void FALCON_build_request_field_9( );
void FALCON_build_request_field_10( );
void FALCON_build_request_field_11( );
void FALCON_build_request_field_12( );
void FALCON_build_request_field_13( );
void FALCON_build_request_field_14( );
void FALCON_build_request_field_15( );
void FALCON_build_request_field_16( );
void FALCON_build_request_field_17( );
void FALCON_build_request_field_18( );
void FALCON_build_request_field_19( );
void FALCON_build_request_field_20( );
void FALCON_build_request_field_21( );
void FALCON_build_request_field_22( );
void FALCON_build_request_field_23( );
void FALCON_build_request_field_24( );
void FALCON_build_request_field_25( );
void FALCON_build_request_field_26( );
void FALCON_build_request_field_27( );
void FALCON_build_request_field_28( );
void FALCON_build_request_field_29( );
void FALCON_build_request_field_30( );
void FALCON_build_request_field_31( );
void FALCON_build_request_field_32( );
void FALCON_build_request_field_33( );
void FALCON_build_request_field_34( );
void FALCON_build_request_field_35( );
void FALCON_build_request_field_36( );
void FALCON_build_request_field_37();
void FALCON_build_request_field_38( );
void FALCON_build_request_field_39( );
void FALCON_build_request_field_40( );
void FALCON_build_request_field_41( );
void FALCON_build_request_field_42( );
void FALCON_build_request_field_43( );
void FALCON_build_request_field_44( );
void FALCON_build_request_field_45( );
void FALCON_build_request_field_46( );
void FALCON_build_request_field_47( );
void FALCON_build_request_field_48( );
void FALCON_build_request_field_49( );
void FALCON_build_request_field_50( );
void FALCON_build_request_field_51( );
void FALCON_build_request_field_52( );
void FALCON_build_request_field_53( );
void FALCON_build_request_field_54( );
void FALCON_build_request_field_55( );
void FALCON_build_request_field_56( );
void FALCON_build_request_field_57( );
void FALCON_build_request_field_58( );
void FALCON_build_request_field_59( );
void FALCON_build_request_field_60( );
void FALCON_build_request_field_61( );
void FALCON_build_request_field_62( );
void FALCON_build_request_field_63( );
void FALCON_build_request_field_64( );
void FALCON_build_request_field_65( );
void FALCON_build_request_field_66( );
void FALCON_build_request_field_67( );
void FALCON_build_request_field_68( );
void FALCON_build_request_field_69( );
void FALCON_build_request_field_70( );
void FALCON_build_request_field_71( );
void FALCON_build_request_field_72( );
void FALCON_build_request_field_73( );
void FALCON_build_request_field_74( );
void FALCON_build_request_field_75( );
void FALCON_build_request_field_76( );
void FALCON_build_request_field_77( );
void FALCON_build_request_field_78( );
void FALCON_build_request_field_79( );
void FALCON_build_request_field_80( );
void FALCON_build_request_field_81( );
void FALCON_build_request_field_82( );
void FALCON_build_request_field_83( );
void FALCON_build_request_field_84( );
void FALCON_build_request_field_85( );
void FALCON_build_request_field_86( );
void FALCON_build_request_field_87( );
void FALCON_build_request_field_88( );
void FALCON_build_request_field_89( );
void FALCON_build_request_field_90( );
void FALCON_build_request_field_91( );
void FALCON_build_request_field_92( );
void FALCON_build_request_field_93( );
void FALCON_build_request_field_94( );
void FALCON_build_request_field_95( );
void FALCON_build_request_field_96( );
void FALCON_build_request_field_97( );
void FALCON_build_request_field_98( );
void FALCON_build_request_field_99( );
void FALCON_build_request_field_100( );
void FALCON_build_request_field_101( );
void FALCON_build_request_field_102( );
void FALCON_build_request_field_103( );
void FALCON_build_request_field_104( );
void FALCON_build_request_field_105( );
void FALCON_build_request_field_106( );
void FALCON_build_request_field_107( );
void FALCON_build_request_field_108( );
void FALCON_build_request_field_109( );
void FALCON_build_request_field_110( );
void FALCON_build_request_field_111( );
void FALCON_build_request_field_112( );
void FALCON_build_request_field_113( );
void FALCON_build_request_field_114( );
void FALCON_build_request_field_115( );
void FALCON_build_request_field_116( );
void FALCON_build_request_field_117( );
void FALCON_build_request_field_118( );
void FALCON_build_request_field_119( );
void FALCON_build_request_field_120( );
void FALCON_build_request_field_121( );
void FALCON_build_request_field_122( );
void FALCON_build_request_field_123( );
void FALCON_build_request_field_124( );
void FALCON_build_request_field_125( );
void FALCON_build_request_field_126( );
void FALCON_build_request_field_127( );
void FALCON_build_request_field_128( );
void FALCON_build_request_field_129( );
void FALCON_build_request_field_130( );
void FALCON_build_request_field_131( );
void FALCON_build_request_field_132( );
void FALCON_build_request_field_133( );
void FALCON_build_request_field_134( );
void FALCON_build_request_field_135( );
void FALCON_build_request_field_136( );
void FALCON_build_request_field_137( );
void FALCON_build_request_field_138( );
void FALCON_build_request_field_139( );
void FALCON_build_request_field_140( );
void FALCON_build_request_field_141( );
void FALCON_build_request_field_142( );
void FALCON_build_request_field_143( );
void FALCON_build_request_field_144();
#define MERCHANT_ID_SIZE 16
#define   MAX_FILENAME_SIZE  80
#define   MAX_INI_INFO_SIZE  20


int Convert_Amt_To_Auth_Tx_String_Format
                              (double nAmount, char* strAmount);

void LeftFill_String_With_Character (unsigned int destination_array_size,
                                     char* strAmount,
                                     unsigned char fill_character);

void falcon_log_message( INT dest, INT sev, pCHAR msg, pCHAR func, int details );
INT falcon_Log_error_warning_to_File(pCHAR Error_Buf,int sev, pCHAR func ,int detail);
void falcon_create_Error_Filename();
void falcon_get_error_warning_file_name_path(void);
