//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PinDlg.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PINDLG_DIALOG               102
#define IDS_MUSTVAL                     103
#define IDS_COMERROR                    104
#define IDS_DBERROR                     105
#define IDS_SENDERROR                   106
#define IDC_MSGBLDERROR                 107
#define IDS_PRODUCT_VERSION             108
#define IDR_MAINFRAME                   128
#define IDD_DIALOG                      130
#define IDB_OffLine                     130
#define IDD_COMM_SETUP                  131
#define IDB_OnLine                      131
#define IDD_TPDU_ROUTER                 133
#define IDD_TPDUREC                     135
#define IDD_ROUTREC                     136
#define IDI_LOGO                        140
#define IDB_LOGO                        144
#define IDD_IDLE_LOGIN                  146
#define IDC_9600_RADIO                  1005
#define IDC_19200_RADIO                 1006
#define IDC_38400_RADIO                 1007
#define IDC_BTS8_RADIO                  1008
#define IDC_COM1_RADIO                  1009
#define IDC_COM2_RADIO                  1010
#define IDC_BTS7_RADIO                  1011
#define IDC_PAR_NONE_RADIO              1012
#define IDC_PAR_ODD_RADIO               1013
#define IDC_PAR_EVEN_RADIO              1014
#define IDC_STOPB1_RADIO                1015
#define IDC_STOPB15_RADIO               1016
#define IDC_STOPB2_RADIO                1017
#define IDC_PORT_LBL                    1018
#define IDC_TCPIP_PORT_ED               1019
#define IDC_COMTYPE_COMBO               1020
#define IDC_TCPIP_SETUP_GRB             1021
#define IDC_HOST_GRB                    1022
#define IDC_SERIAL_SETUP_GRB            1023
#define IDC_COM_PORT_GRB                1024
#define IDC_BAUD_RATE_GRB               1025
#define IDC_BYTE_SIZE_GRB               1026
#define IDC_PARITY_GRB                  1027
#define IDC_COMTYPE_LBL                 1028
#define IDC_STOPBITS_GRB                1029
#define IDC_INCOMMING_GRB               1030
#define IDC_OUTGOING_GRB                1031
#define IDC_CONNECT_BUTTON              1032
#define IDC_DISCONNECT_BUTTON           1033
#define IDC_ABOUT_BUTTON                1034
#define IDC_TRACE_CHECK                 1035
#define IDC_INMESSAGE_ED                1036
#define IDC_INTPDU_ED                   1037
#define IDC_INMESLEN_ED                 1038
#define IDC_OUTMESSAGE_ED               1039
#define IDC_OUTTPDU_ED                  1040
#define IDC_OUTMESLEN_ED                1041
#define IDC_TRACE_FNAME_ED              1042
#define IDC_ON_OFF_INDIC                1043
#define IDC_ONOFF_INDICATOR             1043
#define IDC_INTPDU_LBL                  1044
#define IDC_INMESLEN_LBL                1045
#define IDC_OUTTPDU_LBL                 1046
#define IDC_OUTMESLEN_LBL               1047
#define IDC_TRACE_FNAME_LBL             1048
#define IDC_TPDU_TBL_LST                1050
#define IDC_SETBTN                      1050
#define IDC_ROUTER_TBL_LST              1051
#define IDC_TPDUID_LBL                  1052
#define IDC_TRANLEN_LBL                 1053
#define IDC_DESTLEN_LBL                 1054
#define IDC_SRCLEN_LBL                  1055
#define IDC_TPDUSTR_LBL                 1056
#define IDC_DESTQUE_LBL                 1057
#define IDC_APPDESC_LBL                 1058
#define IDC_OFFSET_LBL                  1059
#define IDC_LENGTH_LBL                  1060
#define IDC_DTTYPE_LBL                  1061
#define IDC_LORANGE_LBL                 1062
#define IDC_HIRANGE_LBL                 1063
#define IDC_ROUTER_TBL_GRB              1064
#define IDC_TPDU_TBL_GRB                1065
#define IDC_ADD                         1067
#define IDC_EDIT                        1068
#define IDC_DELETE                      1069
#define IDC_TPDUID                      1070
#define IDC_TRANSLEN                    1071
#define IDC_DESTLEN                     1072
#define IDC_SRCLEN                      1073
#define IDC_TPDUSTR                     1074
#define IDC_TRANSLEN_LBL                1075
#define IDC_DATATYPE_LBL                1077
#define IDC_DESTQUE                     1078
#define IDC_APPDESC                     1079
#define IDC_OFFSET                      1080
#define IDC_LENGTH                      1081
#define IDC_LORANGE                     1082
#define IDC_HIRANGE                     1083
#define IDC_DATATYPE                    1084
#define IDC_RETRIES                     1086
#define IDC_EXTENDCOMMS                 1086
#define IDC_CLOSE1                      1088
#define IDC_CLOSE2                      1090
#define IDC_CLOSE0                      1091
#define IDC_APPLY1                      1092
#define IDC_APPLY2                      1093
#define IDC_APPLY0                      1094
#define IDC_HELP1                       1095
#define IDC_HELP0                       1096
#define IDC_HELP2                       1097
#define IDC_SERVICES_LIST               1098
#define IDC_HOST_PORT_ED                1100
#define IDC_HOST_PORT_NAME_ED           1101
#define IDC_HOST_NAME_ED                1101
#define IDC_DIR_TCP_SETUP_GRB           1102
#define IDC_HOST_PORT_LBL               1103
#define IDC_HOST_NAME_LBL               1104
#define IDC_SERVICE                     1105
#define IDC_REFRESH                     1106
#define IDC_HEADER_LENGTH_ED            1107
#define IDC_HEADER_LENGTH_LBL           1108
#define IDC_CLIENT_SOCKET_RADIO         1117
#define IDC_SERVER_SOCKET_RADIO         1118
#define IDC_SOCKET_TYPE_GRB             1119
#define IDC_WITH_TPDU_RADIO             1120
#define IDC_WITHOUT_TPDU_RADIO          1121
#define IDC_TPDU_GRB                    1122
#define IDC_IGNORE_TPDU_RADIO           1146
#define IDC_EXTENDCOMMS_LBL             1148
#define IDC_COMM_PORT                   1150
#define IDC_SINGLE_THREAD_CHECK         1152
#define IDC_STATIC_USER                 1153
#define IDC_STATIC_PWD                  1154
#define IDC_UID                         1155
#define IDC_PWD                         1156
#define IDC_STATIC_APPVERSION           1156

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1158
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
