/*********************************************************************************
* Module:
*
* Title:
*
* Description:
*
* Application:
*
* Author:
*
* Revision History:
*  
* $Log:   N:\PVCS\PTE\Equitable\ATP_gui\SCHTYPES.H  $
   
      Rev 1.6   Dec 01 2003 11:30:12   lmitchel
   Added AMEX Online Updates - scr1200
   
      Rev 1.5   Jan 05 2000 14:54:20   gbarnes
   Major update. Not updated to PVCS recently.
   PVCS was locked.
   
      Rev 1.1   Sep 22 1999 15:59:18   iarustam
   Added manual batch entry GUI
   
      Rev 1.0   Jul 01 1999 14:18:14   iarustam
   Initial Release
   
      Rev 1.0   Jun 28 1999 13:59:20   iarustam
   Initial Release
   
      Rev 1.2   May 10 1999 11:38:42   dperson
   Added PVCS header
*   
************************************************************************************/

#ifndef __SCHTYPES__
#define __SCHTYPES__


#define TAB_PROFILE  0
#define TAB_JOB      2
#define TAB_APP      1

#define SCHMODE_ADD          1
#define SCHMODE_EDIT         2 
#define SCHMODE_ADD_TEMP     3


#endif