//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace FSOAP.WebReference {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IncomingQueueSoap", Namespace="http://www.ctl.com/webservices/rbs/")]
    public class IncomingQueue : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public IncomingQueue() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["FSOAP.WebReference.IncomingQueue"];
			if ((urlSetting != null)) 
			{
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://192.168.210.78/RBS/WebServices/incoming/IncomingQueue.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ctl.com/webservices/rbs/Send", RequestNamespace="http://www.ctl.com/webservices/rbs/", ResponseNamespace="http://www.ctl.com/webservices/rbs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SendResult Send(string cXmlMsg) {
            object[] results = this.Invoke("Send", new object[] {
                        cXmlMsg});
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSend(string cXmlMsg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Send", new object[] {
                        cXmlMsg}, callback, asyncState);
        }
        
        /// <remarks/>
        public SendResult EndSend(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SendResult)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ctl.com/webservices/rbs/SendAsString", RequestNamespace="http://www.ctl.com/webservices/rbs/", ResponseNamespace="http://www.ctl.com/webservices/rbs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendAsString(string cXmlMsg) {
            object[] results = this.Invoke("SendAsString", new object[] {
                        cXmlMsg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendAsString(string cXmlMsg, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendAsString", new object[] {
                        cXmlMsg}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSendAsString(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctl.com/webservices/rbs/")]
    public class SendResult {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CTL_RBS_SEND_RESULT[] CTL_RBS_SEND_RESULT_GROUP;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ctl.com/webservices/rbs/")]
    public class CTL_RBS_SEND_RESULT {
        
        /// <remarks/>
        public string CTL_RBS_APPLICATION;
        
        /// <remarks/>
        public string CTL_RBS_RULEDOMAIN;
        
        /// <remarks/>
        public string CTL_RBS_CALLERID;
        
        /// <remarks/>
        public string CTL_RBS_CALLERMSGID;
        
        /// <remarks/>
        public bool CTL_RBS_RESULT;
        
        /// <remarks/>
        public string CTL_RBS_RESULT_ID;
        
        /// <remarks/>
        public string CTL_RBS_RESULT_TEXT;
    }
}
