/******************************************************************************
  
       Module: ptecom.h

        Title: Pinnacle Dialog Manager

  Description: Header file includes all data structure definitions
  
  $Log:   N:\PVCS\PTE\Comm Lib\ptecom.h  $
   
      Rev 1.1   Mar 25 1998 15:31:00   drodden
   Reworked the comm library a little to:
     - have an easier set ot headers to use.
     - prototyped all functions in a header for each module.
     - moved the shared type definitions and global variables
       to common.c  (and .h).
     - use PTE basic data types whever possible.
   
   
      Rev 1.0   17 Mar 1998 13:45:08   MSALEH
   Communication Library files - Initial Release

******************************************************************************/

#ifndef PTECOM_H
#define PTECOM_H


#include "common.h"
#include "serial.h"
#include "tcp.h"


#endif
