//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by monitor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MONITOR_FORM                101
#define IDR_MAINFRAME                   128
#define IDR_MONITOTYPE                  129
#define IDD_PRIMARYACCOUNT_SELECTION    131
#define IDD_MONITOR_FORM1               132
#define IDD_ADVICES                     132
#define IDB_TESTOFF                     134
#define IDB_TESTING                     135
#define IDB_NC_RED                      136
#define IDB_NC_GREEN                    137
#define IDB_NC_YELLOW                   138
#define IDR_241                         141
#define IDD_MONITOR_FORM_Orignial       999
#define IDC_NETWORK_STATUS              1001
#define IDC_REFRESH                     1002
#define IDC_ECHOTEST                    1003
#define IDC_LOGOFF                      1004
#define IDC_LOGON                       1005
#define IDC_LOG_MESSAGES                1006
#define IDC_CLOSE                       1007
#define IDC_PRIMARYACCOUNT_LIST         1007
#define IDC_CLEARLOG                    1008
#define IDC_SAVELOG                     1009
#define IDC_SAF                         1010
#define IDC_DIALOG_CONNECT_STATUS       1011
#define IDC_SCROLLBAR2                  1013
#define IDC_SCROLLBAR3                  1014
#define IDC_SCROLLBAR4                  1015
#define IDC_CONTROLLER_ACTIVITY         1016
#define IDC_BUTTON1                     1017
#define IDC_RESET_COUNTS_BUTTON         1017
#define IDC_START_ADVICES               1017
#define IDC_TRAN_ACTIVITY_LIST          1018
#define IDC_SERVICE_NAME_LABEL          1019
#define IDC_CUP_KEY_REQ_BUTTON          1019
#define IDC_RECEIVED_LABEL              1020
#define IDC_CUP_KEY_UPDATE_BUTTON       1020
#define IDC_LOG_DATE_LABEL              1021
#define IDC_LOG_SERVICE_LABEL           1022
#define IDC_SENT_LABEL                  1023
#define IDC_RATE_LABEL                  1024
#define IDC_PING_BUTTON                 1025
#define IDC_PING_DIALOG_BUTTON1         1026
#define IDC_LOG_TYPE_LABEL              1027
#define IDC_LOG_MSG_LABEL               1028
#define IDC_STOP_ADVICES                1028
#define IDC_LOG_TIME_LABEL              1029
#define IDC_EXIT                        1030
#define IDC_CUP_KEY_UPDATE_BUTTON2      1030
#define IDC_CUP_KEY_RELOAD              1030
#define IDC_TEST_BUTTON                 1031
#define IDC_TEST_RESULT                 1032
#define IDC_STATIC_APPVERSION           1033
#define IDC_NC_STATUS                   1033
#define IDC_STATIC_APP_VERSION          1034
#define IDC_CHECK1                      1034
#define IDC_ACQUIRER_OFF                1035
#define IDC_MGT_REQUESTS                1036
#define IDC_STIP_REQUESTS               1037
#define IDC_STIP_REQUESTS2              1038
#define IDC_NET_TRAN_LIST               1039
#define IDC_PING                        1041
#define IDS_PRODUCT_VERSION             61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
