//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TranSearch.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TRANSETYPE                  129
#define IDD_TRAN_INQUIRY                130
#define IDD_IDLE_LOGIN                  131
#define IDD_TRANDETAILS                 213
#define IDC_ACCOUNT_NBR_FLD             1001
#define IDC_MERCHANT_ID_FLD             1002
#define IDC_DEVICE_ID_FLD               1003
#define IDC_DATE_FLD                    1004
#define IDC_TIME_FLD                    1005
#define IDC_LIST                        1011
#define IDC_NEXT_BUTTON                 1012
#define IDC_MESSAGE_LBL                 1013
#define IDC_INQUIRY_BUTTON              1015
#define IDC_DETAILS_BUTTON              1016
#define IDC_TEXT_FLD                    1017
#define IDC_INQUIRY_BUTTON2             1017
#define IDC_TLF_EXTRACT                 1017
#define IDC_DATE_END_FLD                1018
#define IDC_EMV_FLD                     1018
#define IDC_TIME_END_FLD                1019
#define IDC_EMV_FLD2                    1019
#define IDC_AUTH_NUMBER                 1020
#define IDC_EXP_DATE_FLD                1025
#define IDC_ACQUIRING_INST_ID_FLD       1026
#define IDC_FORWARDING_INSTITUTION_ID_FLD 1027
#define IDC_OUTSTANDING_BALANCE_FLD     1028
#define IDC_CREDIT_LIMIT_FLD            1029
#define IDC_OPERATOR_ID_FLD             1030
#define IDC_CURRENCY_CODE_FLD           1031
#define IDC_SYSTEM_DATE_FLD             1032
#define IDC_FG_Result_FLD               1033
#define IDC_VIEW_ACCEPTED_RADIO         1034
#define IDC_BIN_LOW                     1034
#define IDC_VIEW_FAILED_RADIO           1035
#define IDC_BDO_MERC_ACQ_TX             1035
#define IDC_VIEW_ALLRADIO               1036
#define IDC_ORIGINAL_CURRENCY_CODE      1036
#define IDC_RESEND_BUTTON               1037
#define IDC_EARMARKED_AMT               1037
#define IDC_VIEW_FGRAW_RADIO            1038
#define IDC_AUTH_PROFILE                1038
#define IDC_POSTRAN_GROUP               1039
#define IDC_SERVICE_CODE                1039
#define IDC_EMV_RAW_RADIO               1040
#define IDC_VISA_MERCHANT_IND           1040
#define IDC_FGUARDTRAN_GROUP            1041
#define IDC_DIGITAL_COMM_PRG_IND        1041
#define IDC_DIGITAL_ENTRY_IDENTIFIER    1042
#define IDC_CUP_INDICATOR               1043
#define IDC_POS_SEARCH_CHECK            1045
#define IDC_FGUARD_SEARCH_CHECK         1046
#define IDC_FG_Result                   1047
#define IDC_POS_SEARCH_CHECK2           1047
#define IDC_TLF01_STIP_SEARCH           1048
#define IDC_RADIO2                      1049
#define IDC_GROSS_AMOUNT                1050
#define IDC_MONTHLY_AMORT               1051
#define IDC_TERM_LENGTH                 1052
#define IDC_FACTOR                      1053
#define IDC_UID                         1055
#define IDC_PWD                         1056
#define IDC_USER                        1057
#define IDC_PASS                        1058
#define IDC_BUTTON_EXIT                 1060
#define IDC_STATIC_APP_VERSION          1062
#define IDC_MASK_CARD_NUMBER_CHK        1063
#define IDC_CHECK1                      1064
#define IDC_ATP_STIP                    1064
#define IDC_CHECK2                      1065
#define IDC_MERCHANT_OMD                1065
#define IDC_CHECK3                      1066
#define IDC_VOICE_VOD                   1066
#define IDC_CHECK4                      1067
#define IDC_CVV2_Present                1067
#define IDC_SCHEME_STIP                 1068
#define IDC_TO_ATP_STIP                 1069
#define IDC_FRAUD_REAL_TIME             1070
#define IDC_FRAUD_TO                    1071
#define IDC_FRAUD_ONLINE                1072
#define IDC_TERMINAL_ID_FLD             1084
#define IDC_Orginial_Txn_Amount         1085
#define IDC_Original_Txn_Amt_Currency   1086
#define IDC_ECI                         1087
#define IDC_ORI_ECI_REASON              1088
#define IDC_ECI2                        1088
#define IDC_MCC                         1089
#define IDC_ECI3                        1090
#define IDC_Merchant_Name               1091
#define IDC_POS_DATA                    1092
#define IDC_HOST_PROCESSED              1094
#define IDC_CVV_PRESENT                 1096
#define IDC_Validated                   1097
#define IDC_CVV_Validated               1097
#define IDC_CVV                         1099
#define IDC_CVV2_Validated              1100
#define IDC_PIN_Present                 1101
#define IDC_PIN_Validated               1102
#define IDC_ARQC_Present                1103
#define IDC_CAVV_Present                1104
#define IDC_CAVV_Validated              1105
#define IDC_Acquiring_Country           1107
#define IDC_ARQC_VALIDATED              1108
#define IDC_RETRIEVAL_REF_NUM_FLD       1223
#define IDC_TRAN_TYPE_FLD               1224
#define IDC_PROCESSING_CODE_FLD         1225
#define IDC_CARD_NUMBER_FLD             1226
#define IDC_TRAN_AMOUNT_FLD             1227
#define IDC_RESPONSE_CODE_FLD           1228
#define IDC_MERCHANT_ID_FLD1            1229
#define IDC_INVOICE_NUMBER_FLD          1230
#define IDC_SYSTEM_TRACE_NUMBER_FLD     1231
#define IDC_MESSAGE_TYPE                1232
#define IDC_TRAN_TIME_FLD               1233
#define IDC_TRAN_DATE_FLD               1234
#define IDC_AUTH_ID_RESPONSE_FLD        1235
#define IDC_RESPONSE_TEXT_FLD           1236
#define IDC_POS_ENTRY_MODE_FLD          1239
#define IDC_NRID                        1240
#define IDC_ACTION_CODE                 1241
#define IDC_POS_CONDITION_CODE_FLD      1242
#define IDC_SBATCH_TIME                 1243
#define IDC_EXTCOND_CODE                1244
#define IDC_PROCESSING_CODE_FLD_1       1245
#define IDC_POS_ENTRY_MODE_FLD_1        1246
#define IDC_ECI_1                       1247
#define IDC_SETTLEMENT_DATE             1248
#define IDC_MRA_SENT_TIME               1249
#define IDC_POS_CONDITION_CODE_FLD_1    1250
#define IDC_REPLACEMENT_AMOUNT_FLD      1251
#define IDC_EARMARKED_AMT2              1252
#define IDC_SETTLEMENT_AMT              1253
#define IDC_EARMARKED_CURRENCY2         1254
#define IDC_SETTELMENT_CURRENCY         1255
#define IDC_HOSTNAME                    1256
#define IDC_NII                         1257
#define IDC_RESPONSE_CODE_FLDSCHEME     1258
#define IDC_FRAUD_DECISION_CODE         1258
#define IDC_FRAUD_TXN_SENT_MODE         1259
#define IDC_FRAUD_TXN_RECV_MODE         1260
#define IDC_FRAUD_DECISION_CODE1        1261
#define IDC_FRAUD_DECISION_CODE2        1262
#define IDC_FRAUD_DECISION_CODE3        1263
#define IDC_FRAUD_DECISION_CODE4        1264
#define IDC_FRAUD_DECISION_CODE5        1265
#define IDC_FRAUD_DECISION_CODE6        1266
#define IDC_FRAUD_DECISION_CODE7        1267
#define IDC_FRAUD_DECISION_CODE8        1268
#define IDC_FRAUD_DECISION_CODE9        1269
#define IDC_FRAUD_DECISION_CODE10       1270
#define IDC_FRAUD_RESPONSE_TEXT         1271
#define IDD_FRAUD_TRANDETAILS           1272
#define IDC_FRAUD_DECISION_CODE11       1272
#define IDC_EXTCOND_CODE2               1273
#define IDC_FRAUD_DECISION_CODE12       1273
#define IDC_FRAUD_TXN_DETAILS           1274
#define IDC_FRAUD_DECISION_CODE13       1274
#define IDC_FRAUD_FAI_MODE              1275
#define IDC_FRAUD_DECISION_CODE14       1275
#define IDC_FRAUD_TXN_SENT              1276
#define IDC_FRAUD_TXN_RCVD              1277
#define IDC_SCROLLBAR1                  1278
#define IDC_FRAUD_DECISION_CODE15       1278
#define IDC_TLF_EXTRACT                 1279
#define IDC_FRAUD_DECISION_CODE16       1279
#define IDC_FRAUD_ISSUE_LINK            1280
#define IDC_SYSTEM_DATE_TIME            1281
#define IDC_FRAUD_DECISION_CODE17       1281
#define IDD_ADDITIONAL_DETAILS_RES_TXT  1282
#define IDD_VEDQP_DATA_FIELDS           1283
#define IDC_APPLIED_AUTH_CHAR_INDCR     1284
#define IDC_ACCNT_FUNDING_SOURCE        1285
#define IDC_CARD_HOLDER_ID_METHOD       1286
#define IDC_CASHBACK_AMOUNT             1287
#define IDC_MARKET_SPECIFIC_AUTH_INDCR  1288
#define IDC_PRODUCT_ID                  1289
#define IDC_TRANSACTION_IDENTIFIER      1290
#define IDC_VALIDATION_CODE             1291
#define IDC_SPEND_QUALFICATION_INDCR    1292
#define IDC_POS_ENVIRONMENT_FIELD       1293
#define IDC_CAVV_RESULT_CODE            1294
#define IDC_VS_3DS2_TRANSACTIONID       1295
#define IDC_VS_3DS2_AUTH_RESULT_CODE    1296
#define IDC_VS_3DS2_AUTHN_METHOD        1297
#define IDC_VS_3DS2_SECURE_INDCR        1298
#define IDC_VS_RESPONSE_REASON_CODE     1299
#define IDC_VS_STIP_REASON_CODE         1300
#define IDC_VS_MVV_VALUE                1301
#define IDC_MC_MERCH_ADVICE_CODE        1302
#define IDC_MC_TRAN_LNK_IDENTIFIER      1303
#define IDC_MC_PROGRAM_PROTOCOL         1304
#define IDC_MC_DS_TRAN_ID               1305
#define IDC_MC_UCAF_VALUE               1306
#define IDC_MC_MERCH_CTRY_OF_ORIGIN     1307
#define IDC_MC_PAYMT_ACCNT_REFERENCE    1308
#define IDC_MC_TCC_VALUE                1309
#define IDC_MC_MERCH_PAYMT_GWAY_ID      1310
#define IDC_MC_SANCTION_SCORE_ADDL_INFO 1311
#define IDC_MC_ON_BEHALF_OF_SERVICE     1312
#define IDC_MC_TRANSACTION_PURPOSE      1313
#define IDC_DCI_FUNCTION_CODE           1314
#define IDC_DCI_ERR_DATA_ELEMENT_VALUE  1315
#define IDC_DCI_ADDL_AUTH_DATA          1316
#define IDC_AMX_ECI_VALUE               1317
#define IDC_AMX_AEVV_VALUE              1318
#define IDC_AMX_TRNSN_ID                1319
#define IDC_AMX_3DS2_VERSION            1320
#define IDC_CUP_AVN_VALUE               1321
#define IDC_CUP_DS_TRANID               1322
#define IDC_CUP_SECRTY_RISK_INFO_IP_VALUE 1323
#define IDC_CUP_3DS2_VERSION            1324
#define IDC_CUP_ECI_VALUE               1325
#define IDC_CUP_USAGE_AM_VALUE          1326
#define IDC_JCB_CAVV_VALUE              1327
#define IDC_JCB_ECI_VALUE               1328
#define IDC_JCB_3DS2_VERSION            1329
#define IDC_PHYSICAL_TERM_SERL_NUMBER   1330
#define IDC_PIN_SERVICE_CODE			1331
#define IDC_MC_SECRTY_SRVCS_INFO		1332
#define IDS_PRODUCT_VERSION             61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
