//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TPSR_GUI.rc
//
#define IDRESET                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TPSR_GUI_DIALOG             102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_TEST_PROFILE                129
#define IDB_SAVE                        133
#define IDB_REMOVE                      134
#define IDB_RESET                       135
#define IDR_MENU1                       137
#define IDD_SPLASH                      139
#define IDD_CARD_DEV_MERCHANT           140
#define IDD_TPS_GRAPH                   141
#define IDD_POS_CONFIG                  142
#define IDD_TPSR_MAIN                   144
#define IDD_TPSRMAINSHEET               145
#define IDD_DIALOG1                     146
#define IDI_TPSRICON                    148
#define IDD_STATISTIC_DIALOG            149
#define IDD_CARD_TRACK_DATA             151
#define IDC_COMBO1                      1000
#define IDC_CARD_TYPE                   1000
#define IDC_MSG_TYPE                    1001
#define IDC_BITMAP                      1002
#define IDC_CARD_NBR                    1003
#define IDC_EDIT1                       1003
#define IDC_CARD_NBR_LIST_FILE          1003
#define IDC_PROCESSING_CODE             1004
#define IDC_EDIT2                       1004
#define IDC_AMOUNT                      1005
#define IDC_EDIT3                       1005
#define IDC_SYS_TRACE_NBR               1006
#define IDC_EDIT4                       1006
#define IDC_TIME_LOCAL                  1007
#define IDC_EDIT5                       1007
#define IDC_DATE_LOCAL                  1008
#define IDC_EDIT6                       1008
#define IDC_EXP_DATE                    1009
#define IDC_POS_ENTRY_MODE              1010
#define IDC_NII                         1011
#define IDC_POS_COND_CODE               1012
#define IDC_RETRIVAL_REF_NBR            1013
#define IDC_AUTH_ID_RESP                1014
#define IDC_RESP_CODE                   1015
#define IDC_DEVICE_NBR                  1016
#define IDC_DEVICE_NBR_FILE_LIST        1016
#define IDC_ACQUIRER_ID                 1017
#define IDC_PROFILE_NAME                1017
#define IDC_TRACK1_DATA                 1018
#define IDC_TRACK2_DATA                 1019
#define IDC_PIN_DATA                    1020
#define IDC_EMV_DATA                    1021
#define IDC_PRIVATE1                    1022
#define IDC_PRIVATE2                    1023
#define IDC_PRIVATE3                    1024
#define IDC_CHECK1                      1025
#define IDC_TIME_LOCAL_CHECK            1025
#define IDC_CHECK2                      1026
#define IDC_DATE_LOCAL_CHECK            1026
#define IDC_CHECK3                      1027
#define IDC_RETRIVAL_REF_NBR_CHECK      1027
#define IDC_CHECK4                      1028
#define IDC_AUTH_ID_RESP_CHECK          1028
#define IDC_CHECK5                      1029
#define IDC_RESP_CODE_CHECK             1029
#define IDC_CHECK6                      1030
#define IDC_TRACK1_DATA_CHECK           1030
#define IDC_CHECK7                      1031
#define IDC_TRACK2_DATA_CHECK           1031
#define IDC_CHECK8                      1032
#define IDC_PIN_DATA_CHECK              1032
#define IDC_CHECK9                      1033
#define IDC_EMV_DATA_CHECK              1033
#define IDC_CHECK10                     1034
#define IDC_PRIVATE1_CHECK              1034
#define IDC_CHECK11                     1035
#define IDC_PRIVATE2_CHECK              1035
#define IDC_CHECK12                     1036
#define IDC_PRIVATE3_CHECK              1036
#define IDC_BROWSE_CARD_FILE            1037
#define IDC_TIME_LOCAL_STATIC           1039
#define IDC_DATE_LOCAL_STATIC           1040
#define IDC_RETRIVAL_REF_STATIC         1041
#define IDC_AUTH_ID_RESP_STATIC         1042
#define IDC_RESP_CODE_STATIC            1043
#define IDC_TRACK1_STATIC               1044
#define IDC_TRACK2_STATIC               1045
#define IDC_PIN_DATA_STATIC             1046
#define IDC_EMV_STATIC                  1047
#define IDC_PRIVATE1_STATIC             1048
#define IDC_PRIVATE2_STATIC             1049
#define IDC_PRIVATE3_STATIC             1050
#define IDC_CARD_TYPE1                  1051
#define IDC_STATUS                      1052
#define IDC_BROWSE_DEVICE_FILE          1053
#define IDC_TESTLIST                    1054
#define IDADD                           1055
#define IDREMOVE                        1056
#define IDC_TXNS                        1057
#define IDC_NO_OF_RUNS                  1058
#define IDRUN                           1059
#define IDRESETCOUNTER                  1060
#define IDC_RESRECV                     1061
#define IDC_TXNSENT                     1062
#define IDC_TOOL_STATUS                 1063
#define IDC_STATIC_SENT                 1064
#define IDC_STATIC_RECV                 1065
#define IDC_STATIC_TOTAL_SENT           1066
#define IDC_STATIC_TOTAL_RECV           1067
#define IDC_EXIT                        1067
#define IDC_SHOW_CONSOLE                1068
#define IDC_CARDNUMBERS                 1069
#define IDC_RICHEDIT2                   1070
#define IDC_CARD_NUMBERS                1070
#define IDC_TRACK_DATA                  1071
#define ID_MENU_POS_CONFIG              32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
