/************************************************************* MMXOS.H
**
**	Name:		MMXOS.H (WINNT)
**	----
**
**	Title:		Momentum Operating-System Dependent Header File
**	-----
**
**	Description:
**	-----------
**		This file contains operating-system definition, and
**		any dependent '#include' statements for use in all
**		Momentum Software Corporation programs.
**
**	Last Revision:
**	-------------
**	$Revision:   1.0  $
**	$Date:   Oct 14 1999 08:17:38  $
**	$Author:   MSALEH  $
**
**	Revision History:
**	----------------
**
**	Rev   Date		By	 Description
**	---   --------	---  -----------
**
**
**	Copyright (C) Momentum Software Corporation, 1989
**
*********************************************************************/

#ifndef MMXOS_H
#define MMXOS_H MMXOS_H

/*	Common Header File	*/

#include <windows.h>

#include <mmcos.h>

#endif /* MMXOS_H */

/*
** END ******************************************************* MMXOS.H
*/
