//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ArchiveLookup.rc
//
#define IDC_NEXT                        3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ARCHIVELOOKUP_DIALOG        102
#define IDS_PRODUCT_VERSION             102
#define IDR_MAINFRAME                   128
#define IDD_IDLE_LOGIN                  129
#define IDC_UID                         130
#define IDD_AUTH_ADVISORY               130
#define IDC_PWD                         131
#define IDD_BCH01LOOKUP                 131
#define IDC_USER                        132
#define IDD_BCH11LOOKUP                 132
#define IDC_PASS                        133
#define IDD_BCH20LOOKUP                 133
#define IDD_BCH20DETAILS                134
#define IDD_BCH11DETAILS                135
#define IDD_BCH01DETAILS                136
#define IDD_MAINMENU                    138
#define IDD_TRANDETAILS                 213
#define IDC_CARD_NBR                    1000
#define IDC_MERCHANT_ID                 1001
#define IDC_START_DATE                  1002
#define IDC_RETRIEVAL_REF_NUM           1002
#define IDC_END_DATE                    1003
#define IDC_TERMINAL_ID                 1004
#define IDC_AUTH_RESPONSE_ID            1005
#define IDC_OPERATOR_ID                 1006
#define IDC_ARCHIVE_LIST                1007
#define IDC_EDIT1                       1008
#define IDC_EDIT2                       1009
#define IDC_COMBO1                      1010
#define IDC_EDIT4                       1011
#define IDC_EDIT3                       1012
#define IDC_EDIT5                       1013
#define IDC_COMBO2                      1014
#define IDC_EDIT6                       1015
#define IDC_EDIT7                       1016
#define IDC_EDIT8                       1017
#define IDC_EDIT9                       1018
#define IDC_EDIT10                      1019
#define IDC_RICHEDIT1                   1020
#define IDC_EDIT11                      1020
#define IDC_TRANSACTION_ID              1020
#define IDC_AUTH_PROFILE                1020
#define IDC_STATUS                      1021
#define IDC_EDIT12                      1021
#define IDC_CARD_NBR1                   1021
#define IDC_EDIT13                      1022
#define IDC_INVOICE_NBR                 1022
#define IDC_PAUSE                       1023
#define IDC_EDIT14                      1023
#define IDC_STAN                        1023
#define IDC_STOP                        1024
#define IDC_DEVICE_ID                   1024
#define IDC_EDIT15                      1024
#define IDC_EXPDATE                     1024
#define IDC_TRAN_TYPE_FLD               1025
#define IDC_NEXT100                     1025
#define IDC_BATCH_NBR                   1025
#define IDC_EDIT16                      1025
#define IDC_OPENDATE                    1025
#define IDC_RETRIEVAL_REF_NUM_FLD       1026
#define IDC_OPEN_DATE                   1026
#define IDC_EDIT17                      1026
#define IDC_OPENTIME                    1026
#define IDC_PROCESSING_CODE_FLD         1027
#define IDC_CLOSE_DATE                  1027
#define IDC_EDIT18                      1027
#define IDC_TRANSMISSION_TIME           1027
#define IDC_CARD_NUMBER_FLD             1028
#define IDC_BCH01_LIST                  1028
#define IDC_TOTAL_CRD_AMT               1028
#define IDC_EDIT19                      1028
#define IDC_DEF_GROSS_AMT               1028
#define IDC_TRAN_AMOUNT_FLD             1029
#define IDC_TOTAL_CRD_RE_CNT            1029
#define IDC_EDIT20                      1029
#define IDC_PROCESSED                   1029
#define IDC_RESPONSE_CODE_FLD           1030
#define IDC_TOTAL_CRD_RE_AMT            1030
#define IDC_EDIT21                      1030
#define IDC_TERMINAL_ID_FLD             1031
#define IDC_TOTAL_DBT_CNT               1031
#define IDC_EDIT22                      1031
#define IDC_MERCHANT_ID_FLD1            1032
#define IDC_TOTAL_DBT_AMT               1032
#define IDC_EDIT23                      1032
#define IDC_SYSTEM_TRACE_NUMBER_FLD     1033
#define IDC_TOTAL_DBT_RE_CNT            1033
#define IDC_EDIT24                      1033
#define IDC_OUTSTANDING_BALANCE_FLD     1034
#define IDC_TOTAL_VOID_CRD_RE_CNT       1034
#define IDC_EDIT25                      1034
#define IDC_CREDIT_LIMIT_FLD            1035
#define IDC_TOTAL_VOID_CRD_RE_AMT       1035
#define IDC_EDIT26                      1035
#define IDC_OPERATOR_ID_FLD             1036
#define IDC_EDIT27                      1036
#define IDC_FG_Result_FLD               1037
#define IDC_OPEN_TIME                   1037
#define IDC_EDIT28                      1037
#define IDC_INVOICE_NUMBER_FLD          1038
#define IDC_REL_DATE                    1038
#define IDC_EDIT29                      1038
#define IDC_TRAN_TIME_FLD               1039
#define IDC_REL_TIME                    1039
#define IDC_EDIT30                      1039
#define IDC_TRAN_DATE_FLD               1040
#define IDC_BATCH_STATUS                1040
#define IDC_AUTH_ID_RESPONSE_FLD        1041
#define IDC_VISA_ID                     1041
#define IDC_RESPONSE_TEXT_FLD           1042
#define IDC_TOTAL_VOID_CRD_CNT          1042
#define IDC_POS_ENTRY_MODE_FLD          1043
#define IDC_TOTAL_VOID_CRD_AMT          1043
#define IDC_POS_CONDITION_CODE_FLD      1044
#define IDC_TOTAL_DBT_RE_AMT            1044
#define IDC_ACQUIRING_INST_ID_FLD       1045
#define IDC_TOTAL_CRD_CNT               1045
#define IDC_FORWARDING_INSTITUTION_ID_FLD 1046
#define IDC_DEVICE_ID1                  1046
#define IDC_PURGE_DATE                  1046
#define IDC_EXP_DATE_FLD                1047
#define IDC_BATCH_NBR1                  1047
#define IDC_CURRENCY_CODE_FLD           1048
#define IDC_PROCESSING_CODE             1048
#define IDC_SYSTEM_DATE_FLD             1049
#define IDC_TRAN_AMOUNT                 1049
#define IDC_GROSS_AMOUNT                1050
#define IDC_RESPONSE_CODE               1050
#define IDC_MONTHLY_AMORT               1051
#define IDC_AUTH_NUMBER                 1051
#define IDC_TERM_LENGTH                 1052
#define IDC_TRAN_DATE                   1052
#define IDC_FACTOR                      1053
#define IDC_TRAN_TIME                   1053
#define IDC_TEXT_FLD                    1054
#define IDC_TLF01MENU                   1054
#define IDC_PURGE_DATE2                 1054
#define IDC_EMV_FLD                     1055
#define IDC_BCH01MENU                   1055
#define IDC_MESSAGE_LBL                 1056
#define IDC_BCH11MENU                   1056
#define IDC_FG_Result                   1057
#define IDC_BCH20MENU                   1057
#define IDC_REASON_CODE_FLD             1058
#define IDC_CATEGORY_CODE_FLD           1059
#define IDC_Orginial_Txn_Amount         1060
#define IDC_Original_Txn_Amt_Currency   1061
#define IDC_ACQUIRING_AMT_FLD           1062
#define IDC_ACQUIRING_CURRENCY_FLD      1063
#define IDC_LOCATION_FLD                1064
#define IDC_PURGE_DATE_FLD              1065
#define IDC_ECI                         1066
#define IDC_STOP_REGION_FLD             1067
#define IDC_POS_DATA                    1068
#define IDC_EARMARKED_AMT               1069
#define IDC_ORIGINAL_CURRENCY_CODE      1070
#define IDC_BDO_MERC_ACQ_TX             1071
#define IDC_Acquiring_Country           1072
#define IDC_CARD_NAME_FLD               1073
#define IDC_BIN_LOW                     1074
#define IDC_SERVICE_CODE_FLD            1075
#define IDC_CVC_RESULT_CODE_FLD         1076
#define IDC_SERVICE_CODE_FLD2           1077
#define IDC_HOST_PROCESSED              1077
#define IDC_SCHEME_STIP                 1078
#define IDC_ATP_STIP                    1079
#define IDC_VOICE_VOD                   1080
#define IDC_MERCHANT_OMD                1081
#define IDC_CVV_PRESENT                 1082
#define IDC_CVV_Validated               1083
#define IDC_CVV2_Present                1084
#define IDC_CVV2_Validated              1085
#define IDC_PIN_Present                 1086
#define IDC_PIN_Validated               1087
#define IDC_ARQC_Present                1088
#define IDC_ARQC_VALIDATED              1089
#define IDC_CAVV_Present                1090
#define IDC_CAVV_Validated              1091
#define IDC_MASK                        1092
#define IDC_VISA_MERCHANT_IND           1092
#define IDC_DIGITAL_COMM_PRG_IND        1093
#define IDC_ACQUIRING_CURRENCY_FLD4     1094
#define IDC_DIGITAL_ENTRY_IDENTIFIER    1094
#define IDC_TRAN_TYPE_FLD2              1095
#define IDC_TRAN_MESSAGE_TYPE           1095
#define IDC_CUP_INDICATOR_ARC           1096
#define IDC_ORI_ECI_REASOPN             1097
#define IDC_TO_ATP_STIP                 1098

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
