// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#if !defined(AFX_STDAFX_H__45B83D54_6325_44DB_BB45_172AFEE06DE9__INCLUDED_)
#define AFX_STDAFX_H__45B83D54_6325_44DB_BB45_172AFEE06DE9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define VC_EXTRALEAN		// Exclude rarely-used stuff from Windows headers

//#define _WIN32_WINNT 0x0400
#define _WIN32_WINNT 0x0501

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions
#include <afxdisp.h>        // MFC Automation classes
#include <afxdtctl.h>		// MFC support for Internet Explorer 4 Common Controls
#ifndef _AFX_NO_AFXCMN_SUPPORT
#include <afxcmn.h>			// MFC support for Windows Common Controls
#endif // _AFX_NO_AFXCMN_SUPPORT

#define MAX_NAME_LENGTH 25
#define MAX_SESSION_COUNT 20

#define WM_GET_TLF_LIST		WM_USER + 1
#define WM_GET_TLF_NEXT		WM_USER	+ 2
#define WM_GET_TLF_COUNT	WM_USER + 3
#define WM_PAUSE			WM_USER + 4
#define WM_STOP_SEARCH		WM_USER + 5

#define WM_GET_BCH01_LIST		WM_USER + 6
#define WM_GET_BCH01_NEXT		WM_USER	+ 7
#define WM_GET_BCH11_LIST		WM_USER + 8
#define WM_GET_BCH11_NEXT		WM_USER	+ 9
#define WM_GET_BCH20_LIST		WM_USER + 10
#define WM_GET_BCH20_NEXT		WM_USER	+ 11

#define	COL_TRANSACTION_ID				1
#define	COL_ENTRY_TYPE					2
#define	COL_TPDU_ID						3
#define	COL_ISSUER_ID					4
#define	COL_ACQUIRER_ID					5
#define	COL_TX_KEY						6
#define	COL_TERMINAL_ID					7
#define	COL_TERMINAL_TYPE				8
#define	COL_RESPONSE_TEXT				9
#define	COL_CARD_NUM_LEN				10
#define	COL_CARD_NUM					11
#define	COL_EXP_DATE					12
#define	COL_TOTAL_AMOUNT				13
#define	COL_ADD_AMOUNTS					14
#define	COL_INVOICE_NUMBER				15
#define	COL_ORIG_AMOUNT					16
#define	COL_AUTH_NUMBER					17
#define	COL_PROCESSING_CODE				18
#define	COL_SYS_TRACE_AUDIT_NUM			19
#define	COL_ORIG_SYS_TRACE_NUM			20
#define	COL_POS_ENTRY_MODE				21
#define	COL_NII							22
#define	COL_POS_CONDITION_CODE			23
#define	COL_TRACK1						24
#define	COL_TRACK2						25
#define	COL_RETRIEVAL_REF_NUM			26
#define	COL_ORIG_RETRIEVAL_REF_NUM		27
#define	COL_MERCHANT_ID					28
#define	COL_ORIG_MESSAGE				29
#define	COL_SETTLEMENT_TOTAL			30
#define	COL_MESSAGE_TYPE				31
#define	COL_CARD_HOLDER_NAME			32
#define	COL_GENERAL_STATUS				33
#define	COL_ORIGINATOR_QUEUE			34
#define	COL_ORIGINATOR_INFO				35
#define	COL_BATCH_NUMBER				36
#define	COL_RESPONSE_CODE				37
#define	COL_DATE_YYYYMMDD				38
#define	COL_TIME_HHMMSS					39
#define	COL_NUM_SALES					40
#define	COL_SALES_AMOUNT				41
#define	COL_NUM_REFUNDS					42
#define	COL_REFUND_AMOUNT				43
#define	COL_NUM_DBSALES					44
#define	COL_DBSALES_AMOUNT				45
#define	COL_NUM_DBREFUNDS				46
#define	COL_DBREFUND_AMOUNT				47
#define	COL_PIN_BLOCK					48
#define	COL_TAX_AMOUNT					49
#define	COL_TIP_AMOUNT					50
#define	COL_TRAN_START_TIME				51
#define	COL_HOST_START_TIME				52
#define	COL_HOST_FINISH_TIME			53
#define	COL_TRAN_FINISH_TIME			54
#define	COL_SETTLE_FILE_PREFIX			55
#define	COL_RESP_SOURCE_LEN				56
#define	COL_VISA_CHAR_INDICATOR			57
#define	COL_VISA_TRAN_ID				58
#define	COL_VISA_VALIDATION_CODE		59
#define	COL_MCARD_BANKNET_LEN			60
#define	COL_MCARD_BANKNET				61
#define	COL_AGENT_ID_LEN				62
#define	COL_AGENT_ID					63
#define	COL_CVC							64
#define	COL_SETTLEMENT_DATE				65
#define	COL_CATEGORY_CODE				66
#define	COL_CONVERSION_RATE				67
#define	COL_PRODUCT_CODE				68
#define	COL_ODOMETER					69
#define	COL_ORGANIZATION_ID				70
#define	COL_DYNAMIC_KEYCHANGE			71
#define	COL_SOURCE_KEY					72
#define	COL_TXN_CNT						73
#define	COL_DCF01_RETIRED_CWK			74
#define	COL_DEST_KEY					75
#define	COL_NCF01_RETIRED_CWK			76
#define	COL_HANDLER_QUEUE				77
#define	COL_AUTHORIZING_HOST_QUEUE		78
#define	COL_MAX_NET_CONSEC_TMOUTS		79
#define	COL_MAX_ACTIVE_TXNS				80
#define	COL_FORWARDING_INSTITUTION_ID	81
#define	COL_REMOTE_NSP_TYPE				82
#define	COL_KEK							83
#define	COL_ACQUIRING_ID				84
#define	COL_OUTSTANDING_BALANCE			85
#define	COL_CREDIT_LIMIT				86
#define	COL_NFI_NAME					87
#define	COL_NFI_SEQ_NBR					88
#define	COL_NFI_START_DATE				89
#define	COL_NFI_END_DATE				90
#define	COL_RESP_SOURCE					91
#define	COL_DISPENSATION_ORIGIN			92
#define	COL_DISPENSATION_AUTH_1			93
#define	COL_DISPENSATION_AUTH_2			94
#define	COL_UPDATE_MASK					95
#define	COL_TYPE_OF_DATA				96
#define	COL_DOWN_PAYMENT				97
#define	COL_PERIOD						98
#define	COL_INTEREST_RATE				99
#define	COL_TOTAL_INTEREST				100
#define	COL_REDEMPTION_AMOUNT			101
#define	COL_VEHICLE_NUMBER				102
#define	COL_PROFILE						103
#define	COL_NBR_OF_PROD_CODES			104
#define	COL_PRODUCT_CODES_CODE_1		105
#define	COL_PRODUCT_CODES_QUANTITY_1	106
#define	COL_PRODUCT_CODES_AMOUNT_1		107
#define	COL_PRODUCT_CODES_CODE_2		108
#define	COL_PRODUCT_CODES_QUANTITY_2	109
#define	COL_PRODUCT_CODES_AMOUNT_2		110
#define	COL_PRODUCT_CODES_CODE_3		111
#define	COL_PRODUCT_CODES_QUANTITY_3	112
#define	COL_PRODUCT_CODES_AMOUNT_3		113
#define	COL_PRODUCT_CODES_CODE_4		114
#define	COL_PRODUCT_CODES_QUANTITY_4	115
#define	COL_PRODUCT_CODES_AMOUNT_4		116
#define	COL_PRODUCT_CODES_CODE_5		117
#define	COL_PRODUCT_CODES_QUANTITY_5	118
#define	COL_PRODUCT_CODES_AMOUNT_5		119
#define	COL_PRODUCT_CODES_CODE_6		120
#define	COL_PRODUCT_CODES_QUANTITY_6	121
#define	COL_PRODUCT_CODES_AMOUNT_6		122
#define	COL_PRODUCT_CODES_CODE_7		123
#define	COL_PRODUCT_CODES_QUANTITY_7	124
#define	COL_PRODUCT_CODES_AMOUNT_7		125
#define	COL_PRODUCT_CODES_CODE_8		126
#define	COL_PRODUCT_CODES_QUANTITY_8	127
#define	COL_PRODUCT_CODES_AMOUNT_8		128
#define	COL_PRODUCT_CODES_CODE_9		129
#define	COL_PRODUCT_CODES_QUANTITY_9	130
#define	COL_PRODUCT_CODES_AMOUNT_9		131
#define	COL_PRODUCT_CODES_CODE_10		132
#define	COL_PRODUCT_CODES_QUANTITY_10	133
#define	COL_PRODUCT_CODES_AMOUNT_10		134
#define	COL_PRODUCT_CODES_CODE_11		135
#define	COL_PRODUCT_CODES_QUANTITY_11	136
#define	COL_PRODUCT_CODES_AMOUNT_11		137
#define	COL_PRODUCT_CODES_CODE_12		138
#define	COL_PRODUCT_CODES_QUANTITY_12	139
#define	COL_PRODUCT_CODES_AMOUNT_12		140
#define	COL_PRODUCT_CODES_CODE_13		141
#define	COL_PRODUCT_CODES_QUANTITY_13	142
#define	COL_PRODUCT_CODES_AMOUNT_13		143
#define	COL_PRODUCT_CODES_CODE_14		144
#define	COL_PRODUCT_CODES_QUANTITY_14	145
#define	COL_PRODUCT_CODES_AMOUNT_14		146
#define	COL_PRODUCT_CODES_CODE_15		147
#define	COL_PRODUCT_CODES_QUANTITY_15	148
#define	COL_PRODUCT_CODES_AMOUNT_15		149
#define	COL_PRODUCT_CODES_CODE_16		150
#define	COL_PRODUCT_CODES_QUANTITY_16	151
#define	COL_PRODUCT_CODES_AMOUNT_16		152
#define	COL_PRODUCT_CODES_CODE_17		153
#define	COL_PRODUCT_CODES_QUANTITY_17	154
#define	COL_PRODUCT_CODES_AMOUNT_17		155
#define	COL_PRODUCT_CODES_CODE_18		156
#define	COL_PRODUCT_CODES_QUANTITY_18	157
#define	COL_PRODUCT_CODES_AMOUNT_18		158
#define	COL_PRODUCT_CODES_CODE_19		159
#define	COL_PRODUCT_CODES_QUANTITY_19	160
#define	COL_PRODUCT_CODES_AMOUNT_19		161
#define	COL_PRODUCT_CODES_CODE_20		162
#define	COL_PRODUCT_CODES_QUANTITY_20	163
#define	COL_PRODUCT_CODES_AMOUNT_20		164
#define	COL_VISA_MERCHANT_ID			165
#define	COL_CASH_BONUS					166
#define	COL_DEFERRED_FACTOR				167
#define	COL_DEFERRED_TERM_LENGTH		168
#define	COL_CURRENCY_CODE				169
#define	COL_TRANSMISSION_TIMESTAMP		170
#define	COL_TRAN_FEE_AMOUNT				171
#define	COL_CVC_DATA					172
#define	COL_VERIFY_MAG_STRIPE			173
#define	COL_SAF							174
#define	COL_SECURITY_RESPONSE_CODE		175
#define	COL_SERVICE_CODE				176
#define	COL_SOURCE_PIN_FORMAT			177
#define	COL_DEST_PIN_FORMAT				178
#define	COL_VOICE_AUTH					179
#define	COL_ACTUAL_AMOUNT				180
#define	COL_REVERSAL_AMOUNT				181
#define	COL_VOICE_AUTH_TEXT				182
#define	COL_OPERATOR_ID					183
#define	COL_WORKSTATION					184
#define	COL_ORIG_AUTH_NUMBER			185
#define	COL_TICKET_NBR					186
#define	COL_SYSTEM_DATE					187
#define	COL_DEF_GROSS_AMT				188
#define	COL_MONTHLY_AMORT_AMT			189


void UpdateTitleWithVersion(CDialog *pDlg);


//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STDAFX_H__45B83D54_6325_44DB_BB45_172AFEE06DE9__INCLUDED_)
